// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZZqPu759RjMymSIxHSUKWolSchbrvZpU',
    appId: '1:678663143276:web:37df291c8a1a6c1729fd49',
    messagingSenderId: '678663143276',
    projectId: 'gtg-now',
    authDomain: 'gtg-now.firebaseapp.com',
    storageBucket: 'gtg-now.firebasestorage.app',
    measurementId: 'G-E4NNEF690J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATHDMKMnEfc8fyDInQ7HrwPpKhTvFAjYg',
    appId: '1:678663143276:android:0f2e9a020ab5730329fd49',
    messagingSenderId: '678663143276',
    projectId: 'gtg-now',
    storageBucket: 'gtg-now.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_MKOTsKMOyTdiBnUWX7-1vrVz681PIXk',
    appId: '1:678663143276:ios:35f9c3a75ad4b1bb29fd49',
    messagingSenderId: '678663143276',
    projectId: 'gtg-now',
    storageBucket: 'gtg-now.firebasestorage.app',
    iosBundleId: 'com.example.gtg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_MKOTsKMOyTdiBnUWX7-1vrVz681PIXk',
    appId: '1:678663143276:ios:35f9c3a75ad4b1bb29fd49',
    messagingSenderId: '678663143276',
    projectId: 'gtg-now',
    storageBucket: 'gtg-now.firebasestorage.app',
    iosBundleId: 'com.example.gtg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZZqPu759RjMymSIxHSUKWolSchbrvZpU',
    appId: '1:678663143276:web:8c44a3b5bc2f8b6529fd49',
    messagingSenderId: '678663143276',
    projectId: 'gtg-now',
    authDomain: 'gtg-now.firebaseapp.com',
    storageBucket: 'gtg-now.firebasestorage.app',
    measurementId: 'G-XNLLSZPBGB',
  );

}