// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnRHzlJuFpaju0SNq5LWLI4Svloqp4qL4',
    appId: '1:946045678627:web:b41f54124524288ad36d96',
    messagingSenderId: '946045678627',
    projectId: 'goodtog-b1420',
    authDomain: 'goodtog-b1420.firebaseapp.com',
    storageBucket: 'goodtog-b1420.firebasestorage.app',
    measurementId: 'G-H22KWTFG0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI_SmEG7K3-ZRBOB76kYaWYCD1_zmXr8A',
    appId: '1:946045678627:android:f93eb17e3502ff4ed36d96',
    messagingSenderId: '946045678627',
    projectId: 'goodtog-b1420',
    storageBucket: 'goodtog-b1420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjWrccLTBnjoiNpdNFsG7cg__Dc9tPw7Q',
    appId: '1:946045678627:ios:499099b273a01b59d36d96',
    messagingSenderId: '946045678627',
    projectId: 'goodtog-b1420',
    storageBucket: 'goodtog-b1420.firebasestorage.app',
    iosBundleId: 'com.example.gtg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjWrccLTBnjoiNpdNFsG7cg__Dc9tPw7Q',
    appId: '1:946045678627:ios:499099b273a01b59d36d96',
    messagingSenderId: '946045678627',
    projectId: 'goodtog-b1420',
    storageBucket: 'goodtog-b1420.firebasestorage.app',
    iosBundleId: 'com.example.gtg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnRHzlJuFpaju0SNq5LWLI4Svloqp4qL4',
    appId: '1:946045678627:web:e03203c6c72eff13d36d96',
    messagingSenderId: '946045678627',
    projectId: 'goodtog-b1420',
    authDomain: 'goodtog-b1420.firebaseapp.com',
    storageBucket: 'goodtog-b1420.firebasestorage.app',
    measurementId: 'G-XNN19RMMLT',
  );
}
